#!/usr/bin/env bash
# Serve a web page using nginx
apt update -y
apt install -y nginx

echo "Holberton School" > /var/www/html/index.html

LINE="\\\trewrite ^/redirect_me https://github.com/elfinalist permanent;"
sed -i "24i $LINE" /etc/nginx/sites-available/default

service nginx restart
:x
