#!/usr/bin/env bash
# prints numbers 1-20, but "bad luck" and "China", "Japan", "and "Italy" for 4th, 9th, and 17th iterations respectively
i=1
while (( i <= 20 ))
do
	echo $i
	case $i in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	((i++))
done
