#!/usr/bin/env bash
# Install the ufw firewall and setup a few rules
apt upgrade -y
apt install ufw -y
ufw default deny incoming
ufw disable
ufw allow http
ufw allow ssh
ufw allow https 
ufw --force enable
